app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Se souvenir de moi ') 
    submit = SubmitField('Se connecter')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),Email()])
    username = StringField('Username', validators=[ DataRequired(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
               'Usernames must have only letters, numbers, dots or '
               'underscores')])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password2', message='Passwords must match.')]) 
    password2 = PasswordField('Confirm password', validators=[DataRequired()]) 
    submit = SubmitField('Register')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__) 
from . import views, errors

app/main/views.py
from flask import render_template, session, redirect, url_for, flash, request
from . import main
from flask_login import login_required, login_user, logout_user, current_user
from .forms import LoginForm, RegistrationForm
from ..models import User
from .. import db     

@main.route('/accueil', methods=['GET'])
@login_required
def accueil():
    auth=False
    return render_template('main/mainviews/accueil.html', auth=auth)

@main.route('/', methods=['GET','POST']) 
def login():
    if current_user.is_authenticated:
        return render_template('main/mainviews/accueil.html')
    else: 
        fl = LoginForm()
        if fl.validate_on_submit():
            user = User.query.filter_by(email=fl.email.data).first()
            if user is not None and user.verify_password(fl.password.data):
                login_user(user, fl.remember_me.data) 
                next = request.args.get('next')
                if next is None or not next.startswith('/'):
                    next = url_for('main.accueil') 
                return redirect(next)
            flash('Invalid username or password.')
        return render_template('main/users_management/login.html',form=fl)
 
     
    

@main.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash('Déconnexion réussie.') 
    return redirect(url_for('main.login'))

@main.route('/register', methods=['GET', 'POST']) 
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Inscription réussie. Veuillez vous authentifier à présent.')
        return redirect(url_for('main.login'))
    return render_template('main/users_management/register.html', form=form)

app/templates/main/mainviews/accueil.html
{% extends "base.html" %}
{% block content %}
    <div class='col-lg-6' >
            <h1>Bienvenue au B-D immobiliere</h1>
            <div class='col-lg-12'>
                <h4>Cette application est une application de gestion de l'Immobiler.
                    Elle permet d'enregistrer des Biens Immobiler avec la description de leur proprietaire
                    et de connaitre chacon son proprietaire.
                    
                </h4>
            </div>
        </div>
        
        <div class='col-lg-6' >
            <!-- <img src="{{ url_for('static', filename='img/immobilier2.jpg') }}" alt="..." class="img-circle"> -->
            
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
              
                <!-- Wrapper for slides -->
                <div class="carousel-inner img-circle" role="listbox">
                  <div class="item active">
                    <img src="{{ url_for('static', filename='img/immobilier1.jpg') }}" alt="...">
                    <div class="carousel-caption">
                      ...
                    </div>
                  </div>
                  <div class="item">
                    <img src="{{ url_for('static', filename='img/img5.jpg') }}" alt="...">
                    <div class="carousel-caption">
                      ...
                    </div>
                  </div>
                  <div class="item">
                    <img src="{{ url_for('static', filename='img/img4.jpg') }}" alt="...">
                    <div class="carousel-caption">
                      ...
                    </div>
                  </div>
                  ...
                </div>
              
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>



        </div>
        
{% endblock %}
{% block authentification %}
        {% if current_user.is_authenticated %}
            <li><a href="#">Mon profil</a></li>
            <li><a href="{{ url_for('main.logout') }}">Déconexion</a></li>
        {% else %}
            <li><a href="{{ url_for('main.login') }}">Connexion</a></li>
        {% endif %}
{% endblock %}
{% block bienvenue %}
    {% if current_user.is_authenticated %}
        Bienvenue {{current_user.username}} 
    {% endif %}
{% endblock %}